// Load
export const APP_LOAD = "APP_LOAD";
// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

// Request HTTP
export const AUTH_UPDATE_MVP = "AUTH_UPDATE_MVP";
export const AUTH_UPDATE_PIN = "AUTH_UPDATE_PIN";
export const AUTH_UPDATE_WALLET = "AUTH_UPDATE_WALLET";
export const INIT_REQUEST_STAT = "INIT_REQUEST_STAT";
export const FAIL_REQUEST_STAT = "FAIL_REQUEST_STAT";

// SPINNER
export const SHOW_SPINNER = "SHOW_SPINNER"
export const HIDE_SPINNER = "HIDE_SPINNER"

// DIALOG
export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

// TIMER
export const TIME_REQUEST = "TIME_REQUEST";
export const TIME_RESET = "TIME_RESET";