require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MileVerse' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  target 'MileVerseTests' do
    inherit! :complete
  
  pod 'Firebase/Analytics'
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MileVerse-tvOS' do
  # Pods for MileVerse-tvOS

  target 'MileVerse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
